const quotes = [
    "The journey of a thousand miles begins with one step. – Lao Tzu",
    "Do what you can, with what you have, where you are. – Theodore Roosevelt",
    "Happiness depends upon ourselves. – Aristotle",
    "Believe you can and you're halfway there. – Theodore Roosevelt",
    "Act as if what you do makes a difference. It does. – William James",
    "Success is not how high you have climbed, but how you make a positive difference. – Roy T. Bennett",
    "Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis",
    "The only way to do great work is to love what you do. – Steve Jobs",
    "Your time is limited, so don’t waste it living someone else’s life. – Steve Jobs",
    "It does not matter how slowly you go as long as you do not stop. – Confucius",
    "In the middle of difficulty lies opportunity. – Albert Einstein",
    "Don't watch the clock; do what it does. Keep going. – Sam Levenson",
    "Perseverance is not a long race; it is many short races one after the other. – Walter Elliot",
    "The best way to predict the future is to create it. – Peter Drucker",
    "Courage is resistance to fear, mastery of fear, not absence of fear. – Mark Twain",
    "The secret of getting ahead is getting started. – Mark Twain",
    "Quality means doing it right when no one is looking. – Henry Ford",
    "It is not in the stars to hold our destiny but in ourselves. – William Shakespeare",
    "Opportunities don't happen. You create them. – Chris Grosser",
    "The way to get started is to quit talking and begin doing. – Walt Disney",
    "You miss 100% of the shots you don’t take. – Wayne Gretzky",
    "Don’t let yesterday take up too much of today. – Will Rogers",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. – Winston Churchill",
    "Do what you feel in your heart to be right – for you’ll be criticized anyway. – Eleanor Roosevelt",
    "I have not failed. I've just found 10,000 ways that won't work. – Thomas Edison",
    "You only live once, but if you do it right, once is enough. – Mae West",
    "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
    "Work hard in silence, let success make the noise. – Frank Ocean",
    "Be not afraid of growing slowly, be afraid only of standing still. – Chinese Proverb",
    "Little by little, one travels far. – J.R.R. Tolkien",
    "Every moment is a fresh beginning. – T.S. Eliot",
    "It always seems impossible until it’s done. – Nelson Mandela",
    "If opportunity doesn’t knock, build a door. – Milton Berle",
    "Difficulties in life are intended to make us better, not bitter. – Dan Reeves",
    "Your limitation—it's only your imagination. – Unknown",
    "Push yourself, because no one else is going to do it for you. – Unknown",
    "Great things never come from comfort zones. – Unknown",
    "Dream it. Wish it. Do it. – Unknown",
    "Success doesn’t just find you. You have to go out and get it. – Unknown",
    "The harder you work for something, the greater you’ll feel when you achieve it. – Unknown",
    "Dream bigger. Do bigger. – Unknown",
    "Don’t stop when you’re tired. Stop when you’re done. – Unknown",
    "Wake up with determination. Go to bed with satisfaction. – Unknown",
    "Do something today that your future self will thank you for. – Unknown",
    "Little things make big days. – Unknown",
    "It’s going to be hard, but hard does not mean impossible. – Unknown",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths. – Unknown",
    "The key to success is to focus on goals, not obstacles. – Unknown",
    "Dream it. Believe it. Build it. – Unknown",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit. – Aristotle",
    "The mind is everything. What you think you become. – Buddha",
    "You become what you believe. – Oprah Winfrey",
    "Doubt kills more dreams than failure ever will. – Suzy Kassem",
    "Do what you love and you’ll never work a day in your life. – Confucius",
    "If you want to achieve greatness stop asking for permission. – Unknown",
    "Live as if you were to die tomorrow. Learn as if you were to live forever. – Mahatma Gandhi",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson",
    "Opportunities multiply as they are seized. – Sun Tzu",
    "Your attitude, not your aptitude, will determine your altitude. – Zig Ziglar",
    "A champion is defined not by their wins but by how they can recover when they fall. – Serena Williams",
    "Never let the fear of striking out keep you from playing the game. – Babe Ruth",
    "You must do the thing you think you cannot do. – Eleanor Roosevelt",
    "Happiness is not something ready-made. It comes from your own actions. – Dalai Lama",
    "Make each day your masterpiece. – John Wooden",
    "No one can make you feel inferior without your consent. – Eleanor Roosevelt",
    "If you can dream it, you can do it. – Walt Disney",
    "The best way out is always through. – Robert Frost",
    "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
    "A year from now you may wish you had started today. – Karen Lamb",
    "It's not whether you get knocked down, it's whether you get up. – Vince Lombardi",
    "Do something wonderful, people may imitate it. – Albert Schweitzer",
    "Discipline is the bridge between goals and accomplishment. – Jim Rohn",
    "It’s not about ideas. It’s about making ideas happen. – Scott Belsky",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. – Jim Rohn",
    "Keep going. Everything you need will come to you at the perfect time. – Unknown",
    "Every champion was once a contender that refused to give up. – Rocky Balboa",
    "Stay hungry. Stay foolish. – Steve Jobs",
    "A winner is a dreamer who never gives up. – Nelson Mandela",
    "Difficult roads often lead to beautiful destinations. – Unknown",
    "Today is your opportunity to build the tomorrow you want. – Ken Poirot",
    "Strive not to be a success, but rather to be of value. – Albert Einstein",
    "It is better to fail in originality than to succeed in imitation. – Herman Melville",
    "Failure will never overtake me if my determination to succeed is strong enough. – Og Mandino",
    "Only those who dare to fail greatly can ever achieve greatly. – Robert F. Kennedy",
    "If you fell down yesterday, stand up today. – H.G. Wells",
    "Success is not in what you have, but who you are. – Bo Bennett",
    "Aim for the moon. If you miss, you may hit a star. – W. Clement Stone",
    "Everything you can imagine is real. – Pablo Picasso"
  ];
  
  export default quotes;
  